language: node_js
node_js:
- 12.13.0
env:
  global:
  - KUBECONFIG="/etc/deploy/config"
  - CONTAINER_NAME="lokalvert.tech/${TRAVIS_REPO_SLUG}:${TRAVIS_COMMIT}"
jobs:
  include:
  - stage: Before All
    script:
    - eval "$(ssh-agent -s)"
    - chmod 600 ./deploy_key
    - echo -e "Host lokalvert.tech\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - ssh-add ./deploy_key
    - ssh -i ./deploy_key pi@lokalvert.tech touch helloworld.txt
  - stage: Quality
    name: ESLint
    script: npm run lint
  - stage: Test
    name: Unit-test
    script: npm run test:coverage
  - stage: Dependency Audit
    script: npm audit
before_install:
- openssl aes-256-cbc -K $encrypted_be9d29cb2b88_key -iv $encrypted_be9d29cb2b88_iv
  -in deploy_key.enc -out ./deploy_key -d
